import Foundation
import Testing

@testable import KokoroTTS

/// Compares our G2P output against Kokoro's Python Misaki reference.
///
/// Reference phonemes generated by:
///   from kokoro import KPipeline
///   pipeline = KPipeline('a')
///   phonemes, _ = pipeline.g2p(text)
@Suite("G2P Reference Comparison")
struct G2PReferenceTests {
    struct ReferenceEntry: Decodable {
        let text: String
        let phonemes: String
    }

    // OOV words where our BART-tiny model produces a different (but valid)
    // pronunciation than Python Misaki's larger BART model.
    static let bartDivergences: Set<String> = [
        "AVKubernetesPlayer is a class."
    ]

    // swiftlint:disable force_try
    static let references: [ReferenceEntry] = {
        let url = Bundle.module.url(forResource: "kokoro_g2p_reference", withExtension: "json")!
        let data = try! Data(contentsOf: url)
        return try! JSONDecoder().decode([ReferenceEntry].self, from: data)
    }()
    // swiftlint:enable force_try

    @Test("G2P matches Python Misaki reference", arguments: references)
    func matchesReference(entry: ReferenceEntry) {
        let g2p = EnglishG2P(british: false)
        let (phonemes, _) = g2p.phonemize(text: entry.text)

        if Self.bartDivergences.contains(entry.text) {
            withKnownIssue("BART-tiny model produces different OOV pronunciation") {
                #expect(phonemes == entry.phonemes)
            }
        } else {
            #expect(phonemes == entry.phonemes)
        }
    }
}

extension G2PReferenceTests.ReferenceEntry: CustomTestStringConvertible {
    var testDescription: String { text }
}
